apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  url: https://github.com/fallewi/gitops-fleet-helm
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v2
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: podinfo
  path: "."
  prune: true
  timeout: 1m
